- hosts: all
  tasks:
     - copy:
         src: "{{ item }}"
         dest: /tmp
       with_items:
         - /tmp/test1.txt 
         - /tmp/test2.txt 
         - /tmp/test3.txt 
         - /tmp/test4.txt 
         - /tmp/test5.txt 
         - /tmp/test6.txt 
       