- name: "This is first anisble playbook with yaml"
  hosts: all
  vars:
      mydir: /website_source_code
      file: /tmp/test1.txt
      owner: test_user
      group: test_user
      pkg:
        - httpd
        - nfs-utils
        - tree
        - samba
  tasks:
   - name: "This task is used to create the {{mydir}}" 
     file:
         path: "{{mydir}}"
         state: directory
   - name: "This task is used to copy the file name {{file}}"  
     copy:
         src: "{{file}}"
         dest: /tmp
         owner: "{{owner}}"
         group: "{{group}}" 
   - name: "This task is used to install the {{pkg}}"     
     yum:
         name: "{{pkg}}"
         state: latest  
     